name: advance_image_picker_plus
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/weta-vn/advance_image_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  flutter_native_image:
    git:
      url: https://github.com/yutae/flutter_native_image.git
      ref: master  

  image: ^4.5.3
  image_cropper: ^9.0.0
  image_editor: ^1.6.0
  path_provider: ^2.1.5
  photo_manager: ^3.6.4
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icon/
